### ISSUE TITLE
您好 按照配置完成后为什么不能显示更新

### ISSUE THREAD

**Issue by lblbk** [huang134/QtSparkleTest#1]
按照readme文档全部设置完成了，也打包了.app可以正常运行，但是点击更新一直报错怎么回事

<img width="268" alt="image" src="https://user-images.githubusercontent.com/26684296/229076106-0f33316c-a889-4f61-ab2b-96cd470b3ea7.png">

麻烦了

**Comment by really-hzy** [comment]
您好，您的邮件我已收到，会尽快给您回复

**Comment by lblbk** [comment]
hhh 抱歉 已经解决了 我路径设置错了:cry
